apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::AWS_ACCOUNT_ID:role/eks-role-devopscorner_poc-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - engineering:ops
      rolearn: arn:aws:iam::AWS_ACCOUNT_ID:user/devops
      username: devops
  mapUsers: |
    - userarn: arn:aws:iam::AWS_ACCOUNT_ID:user/zeroc0d3
      username: zeroc0d3
      groups:
        - system:masters
