apiVersion: v1
kind: Secret
metadata:
  name: laravel-cred
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-10.5.12
    app.kubernetes.io/instance: laravel_app-db
    app.kubernetes.io/managed-by: Helm
  namespace: laravel-app
type: Opaque
data:
  app-key: APP_KEY
  db-user: MARIADB_USER
  db-root-pass: MARIADB_ROOT_PASSWORD
  db-pass: MARIADB_PASSWORD
