##################################################
### STAGING (DEV/UAT) Environment DEVOPSCORNER ###
##################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-10.5.12
    app.kubernetes.io/instance: devopscorner-dev_db
    app.kubernetes.io/managed-by: Helm
  namespace: devopscorner-dev
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWUK   # username
  DB_PASSWORD: cGFzc3cwcmQK   # passw0rd
  DB_HOST: MTI3LjAuMC4xCg==   # 127.0.0.1

---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-10.5.12
    app.kubernetes.io/instance: devopscorner-uat_db
    app.kubernetes.io/managed-by: Helm
  namespace: devopscorner-uat
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWUK   # username
  DB_PASSWORD: cGFzc3cwcmQK   # passw0rd
  DB_HOST: MTI3LjAuMC4xCg==   # 127.0.0.1
