apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: observability
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  volumeMode: Filesystem
  volumeName: grafana-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: observability
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp3
  volumeMode: Filesystem
  volumeName: prometheus-server-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-prometheus-alertmanager-0
  namespace: observability
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: observability
  finalizers:
    - kubernetes.io/pvc-protection
  selfLink: >-
    /api/v1/namespaces/observability/persistentvolumeclaims/storage-prometheus-alertmanager-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  volumeMode: Filesystem
