# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

secret:
  enabled: true
  data:
    .dockerconfigjson: ""
    username: ""
    password: ""

configMap:
  enabled: true
  name: "config-frontend"
  mountPath: /app/core/config
  readOnly: true
  data:
    .app.config.json : |-
        {
           "AppName": "Frontend Helm Template",
           "GRPCTimeout": 10,
           "CacheExpiry": 300,
           "CacheCleanup": 600,
           "DefaultPageLimit": 3,
           "ClientTimeout": 10
        }

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  namespace: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: frontend.internal.service
      paths:
      - path: /
        backend:
          serviceName: frontend.internal.service
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - frontend.internal.service

application:
  enabled: true
  env:
    - name: ALLOWED_ORIGINS
      value: '*'
    - name: PORT
      value: "8080"
    - name: REFRESH_TOKEN_EXPIRE_HOUR
      value: "48"
    - name: TOKEN_EXPIRE_HOUR
      value: "1"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  enabled: false
  select:
    node: ""

tolerations: []

affinity: {}
