---
replicaCount: 1

secret:
  enabled: false
  name: "secret-frontend"
  mountPath: {}
  subPath: {}
  readOnly: true
  data: {}

configMap:
  enabled: true
  name: "config-frontend"
  mountPath: /app/core/config
  readOnly: true
  data:
    .app.config.json : |-
        {
           "AppName": "Frontend Helm Template",
           "GRPCTimeout": 10,
           "CacheExpiry": 300,
           "CacheCleanup": 600,
           "DefaultPageLimit": 3,
           "ClientTimeout": 10
        }

image:
  repository: devopscorner/cicd:alpine
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
  namespace: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ""
      paths: []
  tls: []

application:
  enabled: true
  env:
    - name: HELM_TEMPLATE_NAME
      value: frontend
    - name: ALLOWED_ORIGINS
      value: '*'
    - name: PORT
      value: "8080"
    - name: REFRESH_TOKEN_EXPIRE_HOUR
      value: "48"
    - name: TOKEN_EXPIRE_HOUR
      value: "1"

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  enabled: true
  select:
    node: "default"

tolerations: []

affinity: {}
