apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: laravel-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - devopscorner.online
        - develop.devopscorner.online
      secretName: laravel-kubernetes-tls
  rules:
    - host: devopscorner.online
      http:
        paths:
          - backend:
              serviceName: laravel-kubernetes-lamp
              servicePort: 80
    - host: develop.devopscorner.online
      http:
        paths:
          - backend:
              serviceName: laravel-kubernetes-lamp
              servicePort: 80