mariadb:
  rootPassword: "secretpassword"
  user: "laravel_user"
  password: "secretpassword"
  database: "laravel_db"

php:
  envVars:
    - name: APP_KEY
      value: "base64:KvkVVCKALENqUruV8z6Lf85poviBolKzDxS+swRxxDk="
    - name: DB_DATABASE
      value: "laravel_db"
    - name: DB_USERNAME
      value: "laravel_user"
    - name: DB_PASSWORD
      value: "secretpassword"
