php:
  repository: zeroc0d3/laravel-kubernetes
  pullPolicy: IfNotPresent
  tag: "latest"
  fpmEnabled: false
  envVars:
    - name: APP_ENV
      value: production
    - name: APP_DEBUG
      value: false
    - name: DB_PORT
      value: 3306

service:
  type: ClusterIP
  HTTPPort: 80

  ports:
  - name: laravel-svcaccount
    port: 80
    protocol: TCP
    targetPort: 32150

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  enabled: true
  select:
    node: "laravel"

ingress:
  enabled: true
  domain: develop.devopscorner.online
