apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::${ACCOUNT_ID}:role/eks-role-${EKS_CLUSTER}-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - engineering:ops
      rolearn: arn:aws:iam::${ACCOUNT_ID}:role/devopscorner-Lead
      username: devops
  mapUsers: |
    - userarn: arn:aws:iam::${ACCOUNT_ID}:user/zeroc0d3
      username: zeroc0d3
      groups:
        - system:masters
    - userarn: arn:aws:iam::${ACCOUNT_ID}:user/devops
      username: devops
      groups:
        - system:masters
