apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::085546766396:role/eks-role-devopscorner-staging-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - engineering:ops
      rolearn: arn:aws:iam::085546766396:role/devopscorner-Lead
      username: devops
  mapUsers: |
    - userarn: arn:aws:iam::085546766396:user/devops
      username: devops
      groups:
        - system:masters
