---
##################################################
### STAGING (DEV/UAT) Environment DEVOPSCORNER ###
##################################################
apiVersion: v1
kind: Namespace
metadata:
  name: devopscorner
  labels:
    app.kubernetes.io/name: devopscorner
    app.kubernetes.io/instance: devopscorner

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devopscorner-svcaccount
  namespace: devopscorner
