##################################################
### STAGING (DEV/UAT) Environment DEVOPSCORNER ###
##################################################
apiVersion: v1
kind: Namespace
metadata:
  name: devopscorner
  labels:
    app.kubernetes.io/name: devopscorner
    app.kubernetes.io/instance: devopscorner

---
apiVersion: v1
kind: Secret
metadata:
  name: devopscorner-cred
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.8
    app.kubernetes.io/instance: devopscorner-dev_db
    app.kubernetes.io/managed-by: Helm
  namespace: devopscorner
type: Opaque
data:
  db-user: dXNlcm5hbWUK   # username
  db-pass: cGFzc3cwcmQK   # passw0rd
  db-host: MTI3LjAuMC4xCg==  # 127.0.0.1
