{{- if and .Values.prometheus.enabled .Values.prometheus.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "kube-prometheus.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-prometheus.prometheus.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.prometheus.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.prometheus.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.prometheus.ingress.hostname }}
    - host: {{ .Values.prometheus.ingress.hostname }}
      http:
        paths:
          {{- if .Values.prometheus.ingress.extraPaths }}
          {{- toYaml .Values.prometheus.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.prometheus.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.prometheus.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "kube-prometheus.prometheus.fullname" $) "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.prometheus.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "kube-prometheus.prometheus.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
  {{- if or .Values.prometheus.ingress.tls .Values.prometheus.ingress.extraTls }}
  tls:
    {{- if .Values.prometheus.ingress.tls }}
    - hosts:
        - {{ .Values.prometheus.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.prometheus.ingress.hostname }}
    {{- end }}
    {{- if .Values.prometheus.ingress.extraTls }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.prometheus.ingress.extraTls "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
