{{- if and .Values.prometheus.enabled .Values.prometheus.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "kube-prometheus.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-prometheus.prometheus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: prometheus
      prometheus: {{ template "kube-prometheus.prometheus.fullname" . }}
  {{- if .Values.prometheus.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.prometheus.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
