---
apiVersion: v1
kind: Namespace
metadata:
  name: laravel-app
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/instance: laravel-app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-svcaccount
  namespace: laravel-app
