kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-laravel-access
  namespace: laravel-app
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["patch", "get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscallers"]
    verbs: ["create", "delete", "patch", "update", "get", "watch", "list"]
