apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.namespace }}-rolebinding-micro-registry
  namespace: {{ .Values.serviceAccount.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if .Values.clusterrole.create }}
  name: {{ .Values.serviceAccount.namespace }}-micro-registry
{{- else }}
  name: micro-registry
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}  
