version: "3.6"

#================================================================================================
# NETWORK SETUP
#================================================================================================
networks:
  zeroc0d3_net:
    name: zeroc0d3_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.144.144.0/16

#================================================================================================
# VOLUME SETUP
#================================================================================================
volumes:
  vol_portainer:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_PORTAINER:-/opt/data/docker/portainer2.9}
  vol_mariadb:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_MARIADB:-/opt/data/docker/mariadb10.5}
  vol_phpfpm:
    driver: ${VOLUMES_DRIVER:-local}
    driver_opts:
      o: bind
      type: none
      device: ${DATA_UBUNTU:-/opt/data/docker/phpfpm}

services:
#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    image: dockerframework/portainer:${PORTAINER_VERSION:-2.9}
    container_name: ${CONTAINER_PORTAINER:-zeroc0d3_portainer}
    restart: unless-stopped
    ports:
      - "${PORT_PORTAINER:-5212}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer:/data
    environment:
      - PORTAINER_TEMPLATE=generic
      - PORTAINER_VERSION=${PORTAINER_VERSION:-2.9}
    privileged: true
    networks:
      zeroc0d3_net:
        ipv4_address: ${CONTAINER_IP_PORTAINER:-172.144.144.5}

#================================================================================================
# PHPFPM
#================================================================================================
  phpfpm:
    # image: zeroc0d3/laravel-kubernetes:${LARAVEL_K8S_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_PHPFPM:-zeroc0d3_phpfpm}
    restart: unless-stopped
    ports:
      - "${PORT_PHPFPM:-8000}:80"
    volumes:
      #- /etc/localtime:/etc/localtime:ro   ## Do not use it in mac
      #- /var/run/docker.sock:/var/run/docker.sock
      - ${PHPFPM_TOOLS:-./phpfpm}:/tmp/phpfpm
    environment:
      - TZ="Asia/Jakarta"
      - PHP_VERSION=${PHP_VERSION:-7.4}
      - APP_KEY="base64:KvkVVCKALENqUruV8z6Lf85poviBolKzDxS+swRxxDk="
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_DATABASE=${MARIADB_DATABASE:-laravel_dev}
      - DB_USERNAME=${MARIADB_USER:-laravel_user}
      - DB_PASSWORD=${MARIADB_PASSWORD:-secretpassword}
    privileged: true
    tty: true
    networks:
      zeroc0d3_net:
        ipv4_address: ${CONTAINER_IP_PHPFPM:-172.144.144.200}

#================================================================================================
# MARIADB
#================================================================================================
  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.5.12}
    # build:
    #   context: ./docker/ubuntu-mariadb
    #   dockerfile: Dockerfile
    container_name: ${CONTAINER_MARIADB:-zeroc0d3_mariadb}
    restart: always
    ports:
      - "${PORT_MARIADB:-3306}:3306"
    volumes:
      #- /etc/localtime:/etc/localtime:ro   ## Do not use it in mac
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_mariadb:/var/lib/mysql
      - ./docker/ubuntu-mariadb/rootfs/etc/my.cnf:/etc/my.cnf
      - ./docker/ubuntu-mariadb/rootfs/etc/my.cnf.d/mariadb-server.cnf:/etc/my.cnf.d/mariadb-server.cnf
      ## Path services ##
      - ${SERVICES_TOOLS:-./services}:/tmp/services
    environment:
      - ENV=local
      - TZ="Asia/Jakarta"
      - MYSQL_PROFILE=my-medium
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-secretpassword}
      - MYSQL_ROOT_HOST=${MARIADB_ROOT_HOST:-127.0.0.1}
      - MYSQL_HOST=${MARIADB_HOST:-127.0.0.1}
      - MYSQL_DATABASE=${MARIADB_DATABASE:-laravel_dev}
      - MYSQL_USER=${MARIADB_USER:-laravel_user}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD:-secretpassword}
      #- SKIP_INNODB=1
    privileged: true
    tty: true
    networks:
      zeroc0d3_net:
        ipv4_address: ${CONTAINER_IP_MARIADB:-172.144.144.201}
