{{- if and .Values.alertmanager.enabled .Values.rbac.create .Values.rbac.pspEnabled }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-prometheus.alertmanager.fullname" . }}-psp
  labels: {{- include "kube-prometheus.alertmanager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-prometheus.alertmanager.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-prometheus.alertmanager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
